# Generated by Django 3.1.3 on 2021-01-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('pris', models.BooleanField()),
                ('urgent', models.BooleanField()),
                ('pris_par', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('a', 'A faire'), ('e', 'En cours'), ('t', 'Terminée'), ('z', 'Autre')], default='a', help_text="Choisir l'état d'avancement de la tâche", max_length=50)),
            ],
            options={
                'ordering': ['urgent', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('prenom', models.ForeignKey(default='Inconnu', on_delete=django.db.models.deletion.CASCADE, to='back.user')),
            ],
        ),
    ]
