# Generated by Django 3.1.3 on 2021-01-08 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_message_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deadline',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='prenom',
            field=models.ForeignKey(blank=True, default='Inconnu', on_delete=django.db.models.deletion.RESTRICT, to='back.user'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='pris',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='pris_par',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'A faire'), ('e', 'En cours'), ('t', 'Terminée'), ('z', 'Autre')], default='a', help_text="Choisir l'état d'avancement de la tâche", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
