# Generated by Django 3.1.3 on 2021-01-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20210108_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='prenom',
            field=models.ForeignKey(blank=True, default='Inconnu', on_delete=django.db.models.deletion.SET_DEFAULT, to='back.user'),
        ),
    ]
