# Generated by Django 3.1.3 on 2021-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20210108_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='pris',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
