# Generated by Django 3.1.3 on 2021-01-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20210125_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
