# Generated by Django 3.1.3 on 2021-01-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_auto_20210126_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
    ]
