# Generated by Django 3.1.3 on 2021-01-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_auto_20210126_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='message',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
