# Generated by Django 3.1.3 on 2021-01-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_auto_20210126_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='fait_par',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
