# Generated by Django 3.1.3 on 2021-01-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_auto_20210131_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, default='à faire', help_text="Choisir l'état d'avancement de la tâche", max_length=50),
        ),
    ]
