# Generated by Django 3.1.3 on 2021-02-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20210131_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='tache',
            name='choix_pris_par',
            field=models.ManyToManyField(blank=True, null=True, to='back.User'),
        ),
    ]
