# Generated by Django 3.1.3 on 2021-02-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_recherche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recherche',
        ),
    ]
